###############################
#                             #
#        Prison Craft         #
#        Par Axeno_Off        #
#                             #
#   Configuration du plugin   #
#                             #
###############################


activities:
  list:
    - Activité 1
    - Activité 2
    - Activité 3