################################
#                              #
#           Questify           #
#           By axenq           #
#                              #
#         Plugin Setup         #
#                              #
################################


# Region configuration
regions:
  # Enable or disable zone activity. (Enabled = true, Disabled = false)
  enable: true
  # Name of the region.
  name: "example"


# Activity configuration
activities:
  # Time of activities
  time: 5 # in minutes
  # List of activities
  list:
    activity_1:
      # name of activity
      name: "Activity 1"
      # Color available: BLUE, RED, WHITE, PURPLE, PINK, GREEN, YELLOW
      color: "BLUE"
    activity_2:
      # name of activity
      name: "Activity 2"
      # Color available: BLUE, RED, WHITE, PURPLE, PINK, GREEN, YELLOW
      color: "RED"
    activity_3:
      # name of activity
      name: "Activity 3"
      # Color available: BLUE, RED, WHITE, PURPLE, PINK, GREEN, YELLOW
      color: "WHITE"